<program> ::= <function>
<function> ::= "int" <identifier> "(" "void" ")" "{" <statement> "}"
<statement> ::= "return" <expression> ";"
<expression> ::= <int>
<identifier> ::= ? An identifier token ?
<int> ::= ? A constant token ?